### ISSUE TITLE
LTE AWS (Band 4 1700/2100) Dont work

### ISSUE THREAD

**Issue by gartstell** [z2-dev/android_device_zuk_z2_plus#10]
The phone can't connect to LTE on AWS band (BAND 4, 1700/2100) whit the lastest version (download 02.14.2017). The phone itself support this band. My carrier (Telcel, in Mexico) uses only AWS band for LTE, and only can connect to 3g and H+.

I test with other phones and get LTE working with the same SIM and APN config, so I think maybe is a ROM problem.

EDIT: I try with the basebands from http://zukfans.eu/community/threads/zuk-z2-baseband-collection-versions.4565/ and get LTE working whit all of them, but also dont work the audio call.

**Comment by AlvaroBrey** [comment]
@gartstell I understand LTE is working in latest baseband versions?

**Comment by gartstell** [comment]
LTE is working now with baseband 9-00009-m8996faaaanazm-1.53476.1 on MoKee MK60.1-z2-170214-RELEASE. So is not phone issue, the AWS is fully supported by the phone.

I test all the basebands in the link above (http://zukfans.eu/community/threads/zuk-z2-baseband-collection-versions.4565/) whit your ROM and LTE work with all of them without problems; I noted some variations in signal bar, but maybe was circunstantial; but the phone stops to work making calls: I can dial, even hear the ring tone, but when the call is established, I can't hear anything. 

I switch back to MoKee because Telcel crops the 3g speed so much beyond the technical limit, so make it almost unusable.

I will back tu your ROM when I have more time to play  :)

**Comment by AlvaroBrey** [comment]
Closed as invalid
