### ISSUE TITLE
Image preview (gallery) in camera app not rotating.

### ISSUE THREAD

**Issue by ghost** [z2-dev/android_device_zuk_z2_plus#101]
- ROM build version (date):
  All releases so far?

- Steps to reproduce:

1) Hold your phone vertically
2) Open camera app (Build-in, not a 3th party one)
3) Swipe left (the last picture taken will appear on screen)
4) Now rotate de device.

The image stays as is, and doesn't rotate along with the device.

Now.. I thought.. this might not be a bug, just a non existing feature, but now try this:

1) Close camera app completely
2) Hold your phone horizontally. (Make sure the home button is on the right hand side)
3) Open camera app (Build-in, not a 3th party one)
4) Swipe down (the last picture taken will appear on screen)

But it's being displayed as if you were holding your phone upright, which you aren't.

**Comment by AlvaroBrey** [comment]
This is not a bug, the gallery preview screen simply doesn't have a landscape orientation, at this time it's supposed to be used with the phone held vertically.
It _would_ be a bug if it did have a landscape layout and didn't work,  but it isn't the case. This is more of a feature request for the people who develop Snap.

**Comment by ghost** [comment]
Or maybe it is a bug after all?
I just found this;
https://jira.lineageos.org/browse/BUGBASH-14
