### ISSUE TITLE
Bootloop to twrp recovery after performing an ota update.

### ISSUE THREAD

**Issue by yiyuechen** [z2-dev/android_device_zuk_z2_plus#108]
updated from _lineage-14.1-20170612-UNOFFICIAL-z2_plus_ to _lineage-14.1-20170626-UNOFFICIAL-z2_plus_.     
It keeps looping to the recovery even after I clean Dalvik/ART Cache, Data, SD card, Cache, System and reflash all over.

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
What is your TWRP version? This is a known bug with the LOS OTA updater and older versions of TWRP.

To solve your bootloop you probably have to wipe the `misc` partition.
[Here's how to.](https://zukfans.eu/community/threads/7-1-x-unofficial-lineageos-14-1-20170626.4852/page-54#post-45690)

**Comment by yiyuechen** [comment]
Thank you! It was 3.0.0. And one more thing, the ota update could not run automatically, namely it just booted to recovery and did nothing. So I had to manually dirty flash it. But anyway I solved the bootloop by wiping misc. Now I have switched to the latest version twrp 3.1.1.0. Will these problems reoccur if further OTA update is performed?

**Comment by AlvaroBrey** [comment]
_Theoretically_ everything should work fine on the latest TWRP version, but as always, caution is advised :)
