### ISSUE TITLE
USB notification bug

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#11]
When the phone is started for the first time after a clean flash, a "Supplying power to connected USB device" notification is displayed, even if the phone is not plugged in.
This persists until the phone is actually plugged in.

**Comment by marchi19217** [comment]
This seems to be a Nougat bug;

https://code.google.com/p/android/issues/detail?id=217702

https://www.reddit.com/r/GooglePixel/comments/5f5p8z/usb_supplying_power_to_attached_device_when/
