### ISSUE TITLE
Ambient Display

### ISSUE THREAD

**Issue by ghost** [z2-dev/android_device_zuk_z2_plus#115]
Ambient display does not work properly on my device: 
when it's turned on it only works when I receive a notification but even if the other three tics are selected it does not work in those situations.

- ROM build version (date): 14.1-20170728-UNOFFICIAL-z2_plus
- Steps to reproduce: Setting->display->ambient display->turn everything on, then wait for a notification (you can see the ambient display working), later try to pick up the device (from table or pocket) or hover the hand over the sensor and it will do nothing

**Comment by AlvaroBrey** [comment]
Don't know about the pickup mode, but about the sensor "wave", try this:

1. Lock your phone and wait a couple of seconds
2. Put your finger on the sensor (which is just besides the front camera)
3. Wait a second
4. Lift your finger

The screen should turn on ambient display mode.

¿Does this work for you?

**Comment by ghost** [comment]
no it does not (the option is turned on). I can get the ambient screen to pop just when i receive the notification, can't get it to show with everything else

**Comment by AlvaroBrey** [comment]
@ProThunder

- Does it work in previous releases?
- Have you tried a clean install?
- Does it work in other ROMs (if you have tried any)?

 Does it work for you in other ROMs? (if you have tried others)

**Comment by ghost** [comment]
First time on lineage, Never tried other roms. Clean install was performed

**Comment by ghost** [comment]
after the kernel change it started working

**Comment by AlvaroBrey** [comment]
Good! Closing this then
