### ISSUE TITLE
Kernel panic under high CPU workloads

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#116]
ROM crashes to black screen under high CPU workloads, for example when running AnTuTu CPU test.

This is a known bug with the latest CAF kernel for msm8996.

- ROM build version (date): 20170811

**Comment by jtnmartinho** [comment]
Hi Many thanks for you amazing work. : )

I have the 20170808 build. I updated it from the previously version, only wiped cache and dalvik. No issues to report.

I did a Antutu Benchmark test. I went to battery options and changed profile to performance. I run the test, everything went as expected, no issues at all, and I got a higher score than ever before with your rom: 150k.

**Comment by AlvaroBrey** [comment]
Thanks for your feedback, but this is a known issue with the current msm8996 kernel. It's been patched already and should be fine again for the next release.

Edit: as an aside, I don't really care about AnTuTu scores, only cited it because it causes high CPU workload, so it's an easy way to reproduce the crash.

**Comment by AlvaroBrey** [comment]
Not happening in 20170822
