### ISSUE TITLE
Hello gods. Thank you for doing the ROM, the new kernel is now feeling very power. As well as fluency as before the version, I hope brush lineageos fluency with the more up the more cool Oh Can not integrate zui thing into it? This will Caton is not smooth Oh, thank you, hope you continue to optimize it to refuel. The The The

### ISSUE THREAD

**Issue by lineageos15ken** [z2-dev/android_device_zuk_z2_plus#119]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
What
