### ISSUE TITLE
High power consumption after build 20170811

### ISSUE THREAD

**Issue by lineageos15ken** [z2-dev/android_device_zuk_z2_plus#121]
New kernel power consumption
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by jtnmartinho** [comment]
My phone doesn't enter deep sleep on the latest build (20170811). Other users reported the same issue.

**Comment by VadimDedeiko** [comment]
I confirm.
The new kernel consumes a lot of energy. It does not sleep.
I did a full wipe before installing the last firmware.
So many kernel wakelocks

Build 20170811
[Betterbattery stats](https://drive.google.com/file/d/0B4enmV_N3wLUeGZRUTBUVVZsN0E/view?usp=drivesdk)
[dmesg](https://drive.google.com/file/d/0B4enmV_N3wLUcGVocjJmYW5razQ/view?usp=drivesdk)
[logcat](https://drive.google.com/file/d/0B4enmV_N3wLUbDg1cEFOa0M5bE0/view?usp=drivesdk)

**Comment by IVinJC** [comment]
I'll take tomorrow logcat, dmesg from BetterBatterystats

**Comment by IVinJC** [comment]
https://drive.google.com/file/d/0B4enmV_N3wLUeGZRUTBUVVZsN0E/view?usp=drivesdk

https://drive.google.com/file/d/0B4enmV_N3wLUcGVocjJmYW5razQ/view?usp=drivesdk

https://drive.google.com/file/d/0B4enmV_N3wLUbDg1cEFOa0M5bE0/view?usp=drivesdk

**Comment by VadimDedeiko** [comment]
Awake (Screen Off) (): 8 h 51 m 31 s  100,0%

CPU    worked    307,2 MHz (): 8 h 48 m 9 s  99,3%

**Comment by AlvaroBrey** [comment]
This is caused by the CPU not entering deepsleep, as most of you have reported. If I can't find a solution in a reasonable time, I'll revert back to the old kernel temporarily.

**Comment by lineageos15ken** [comment]
What is the next time? Are you sure to change back to the old kernel? Then I first brush back to 2017.7.28

**Comment by AlvaroBrey** [comment]
I'm not gonna revert back to the old kernel, I found the source of the wakelocks and already patched it.

No ETAs on next release but it shouldnt be very far.

**Comment by AlvaroBrey** [comment]
Reopening until a release with the fix is published

**Comment by AlvaroBrey** [comment]
Closing as build 20170822 reverts back to the old kernel for now
