### ISSUE TITLE
Hangs network on asu 3, there is no possibility to call and receive call, no Internet (SIM1)

### ISSUE THREAD

**Issue by thavron79** [z2-dev/android_device_zuk_z2_plus#122]
- AOSiP 20170809
- modem M8996FAAAANAZM-1.70664.3.76387.1 (clean install on ZUI 412)
- official TWRP 3.1.1-0
- BeansGapps-Mini-7.1.x-20170725
Logcat1 - after a restart 17.08.2017
Logcat2 - after a problem is detected, in 10:18 the connection is working, SMS was received, apparently after some time had frozen.
[logcat1.txt](https://github.com/z2-dev/android_device_zuk_z2_plus/files/1233819/logcat1.txt)
[logcat2.txt](https://github.com/z2-dev/android_device_zuk_z2_plus/files/1233820/logcat2.txt)

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
Why would I take bug reports for a ROM that I don't maintain?
