### ISSUE TITLE
8.11 play the game a huge heat, Caton is not smooth

### ISSUE THREAD

**Issue by lineageos15ken** [z2-dev/android_device_zuk_z2_plus#123]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
If you can't write English, please refrain from opening issues with stuff pasted from a translator.

This is a fair warning. I've seen several of these from you already. The next time you open one like this I will block you.
