### ISSUE TITLE
Mobile data network bug

### ISSUE THREAD

**Issue by FanxJK** [z2-dev/android_device_zuk_z2_plus#126]
I am the Chinese, the current baseband version (1.7) in China's mobile network CMCC has a bug, open and then close the mobile data or there will be a network, hoping to upgrade to the latest baseband

- ROM build version (date):170822 and older, 
- Baseband version: M8996FAAAANAZM-1.70664.3.76387.1
[ramoops.txt](https://github.com/z2-dev/android_device_zuk_z2_plus/files/1245187/ramoops.txt)

**Comment by AlvaroBrey** [comment]
Is this the same issue as #56 ?

**Comment by FanxJK** [comment]
@ontherunvaro Yes, it is the same problem.
I have tested, the baseband changed to: M8996FAAAANAZM-1.76387.1.92759.1 able to repair
This bug is not fixed in the 20170420 version because it has never been fixed

**Comment by AlvaroBrey** [comment]
Closed as duplicate
