### ISSUE TITLE
CALL BUG WITH SECUNDARY USER

### ISSUE THREAD

**Issue by daltonmajewski** [z2-dev/android_device_zuk_z2_plus#128]
using a secondary user, you cant make or receive calls. the cellphone rings, but there is no interface

I'm using a 28/07 build

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
That is an old build, can you try it in 20170904?

**Comment by AlvaroBrey** [comment]
Closed for no response
