### ISSUE TITLE
The latest 0822 build seems to not support CMCC(a network operator in China).

### ISSUE THREAD

**Issue by yiyuechen** [z2-dev/android_device_zuk_z2_plus#129]
Not sure whether the previous ones support CMCC, but 0822 build does not. It shows ''no service|CMCC'' on top. Any suggestions? Thanks.
![screenshot_20170902-192709](https://user-images.githubusercontent.com/17523520/29995157-7150d9f8-9015-11e7-8370-ed4e76cf3ebe.png)

**Comment by AlvaroBrey** [comment]
Is this still happening in latest version (20170904)

**Comment by AlvaroBrey** [comment]
Closing for no response
