### ISSUE TITLE
Camera flash out of sync with photo

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#132]
Flash lights up _before_ the photo is taken, so the photo is dark.

- ROM build version (date): 20170904

**Comment by digitalpriory** [comment]
[2017-09-09-01-08-04.txt](https://github.com/z2-dev/android_device_zuk_z2_plus/files/1289390/2017-09-09-01-08-04.txt)

I thought I was going mad. Already broken my touch screen this week so thank god it isn't hardware!

**Comment by NefixEstrada** [comment]
Do you need more logs?
