### ISSUE TITLE
cpu performance is reduced, not only no power, electricity with faster

### ISSUE THREAD

**Issue by lineageos15ken** [z2-dev/android_device_zuk_z2_plus#134]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by lineageos15ken** [comment]
20170904. Greater power consumption, lower performance, running large-scale application card

**Comment by AlvaroBrey** [comment]
I warned you in your previous issue. You are now banned from posting issues until you learn to write English in an understandable way.
