### ISSUE TITLE
USB OTG not working

### ISSUE THREAD

**Issue by nsr8** [z2-dev/android_device_zuk_z2_plus#135]
however, it is recognized in TWRP. Can mount and flash from USB OTG.

- ROM build version (date): 20170904
- logcat (pastebin link): [https://pastebin.com/f6AAUufr](https://pastebin.com/f6AAUufr)
- Steps to reproduce:
Flash 20170904 after wiping Davlik/Cache/System
Flash Gaaps pico
boot
USB OTG is not recognized

_edit from repo owners: Format_

**Comment by AlvaroBrey** [comment]
What is this logcat of? It's very short and I can't find anything related to USB in it. Did you filter it in any way? If so please provide the full untouched logcat.

**Comment by nsr8** [comment]
Please check the same logcat uploaded at ZeroBin [https://zerobin.net/?d9ad60e8766d8a0a#C7eX1n3S3voDdIjXvVGNxSQ5dPLpBr3i6HpcOCd1hpg=](url)

**Comment by nsr8** [comment]
I'm getting error 404 when I click on the ZeroBin link that I have posted above. This is the link in plain text.

https://zerobin.net/?d9ad60e8766d8a0a#C7eX1n3S3voDdIjXvVGNxSQ5dPLpBr3i6HpcOCd1hpg=

**Comment by AlvaroBrey** [comment]
Readding "needs logs" tag, because the posted logs have expired and I can't see them.

**Comment by nsr8** [comment]
https://zerobin.net/?e1fd574c835ea778#9vImpDlRv1FfuMt8urr2h/kTt6GXXNTHtdkTqXwW/SU=
Logs

**Comment by AlvaroBrey** [comment]
Fixed in 20170930
