### ISSUE TITLE
Google play crash

### ISSUE THREAD

**Issue by gianni1129** [z2-dev/android_device_zuk_z2_plus#137]
It doesn't work anymore

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
If you wipe system you need to flash Gapps again
