### ISSUE TITLE
Hotspot WiFi not workkng

### ISSUE THREAD

**Issue by gianni1129** [z2-dev/android_device_zuk_z2_plus#138]
It gives error message

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
Duplicate of #130
