### ISSUE TITLE
Quick settings torch tile does not work

### ISSUE THREAD

**Issue by nsr8** [z2-dev/android_device_zuk_z2_plus#142]
-build 20170930
-logcat https://zerobin.net/?5f307df32095410a#eS0EN6CUEqQfn2JJ/EZ88lHA+rPxdaqekw+gH0DzauE=
-steps to reproduce
*clean flash the rom after wiping system, dalvik and data
*flash gaaps
*switch on torch from quick settings

(camera flash works flawlessly)

**Comment by IvvanVG** [comment]
I'm ok) build 20170930
![screenshot_20171004-200416](https://user-images.githubusercontent.com/8935752/31174771-4ac8a8b8-a93f-11e7-887e-5dc06b175fab.png)
![screenshot_20171004-200420](https://user-images.githubusercontent.com/8935752/31174788-5a18dd4c-a93f-11e7-9d8e-c743a502d2c6.png)

**Comment by AlvaroBrey** [comment]
Hmm, I tried earlier and it did not work, but now I tried again and it does. Strange. Changing tag to "investigate."
Edit: I think it may have something to do with charging state/battery level

**Comment by IvvanVG** [comment]
I repeated the error when the battery is low. so when you try to turn on the flashlight while the screen is off, pressing the power button. the phone has frozen with a white diode . after reboot everything is fine.

**Comment by nsr8** [comment]
Flash light works now after a reboot. However, there's a slight lag.

Touching the quick settings icon immediately switches on the light and the icon indicates that the light is on. Touching the icon again switches off the light immediately, but the icon indicates it is still on. It takes about 5 seconds to display as off.

A very minor issue. I don't remember if it was the same in previous builds.

Battery status might not be relevant. Flash didn't light up with 90% battery. Now it works at 40%.

I will post a logcat if the issue is reproduced.

**Comment by AlvaroBrey** [comment]
Fixed in 20171120
