### ISSUE TITLE
Slow battery charging

### ISSUE THREAD

**Issue by amitv87** [z2-dev/android_device_zuk_z2_plus#144]
The battery charging current never crosses 880mA on build 20170930.
Works fine with previous builds.

Verified using [ampere app](https://play.google.com/store/apps/details?id=com.gombosdev.ampere&hl=en) from play store.

**Comment by Darkiu** [comment]
It was a change in the kernel, to avoid overheating in the battery

Link: https://github.com/z2-dev/android_kernel_zuk_msm8996/commit/88940502329fcf83da1dd3901a233f298dc40b38

**Comment by AlvaroBrey** [comment]
Check [this](https://github.com/z2-dev/android_kernel_zuk_msm8996/commit/88940502329fcf83da1dd3901a233f298dc40b38).

Seems @Darkiu got ahead of me. As you can see in that commit, current is reduced only while screen is on, to reduce strain on battery.

**Comment by Darkiu** [comment]
jajajaja

**Comment by Darkiu** [comment]
XDDD
