### ISSUE TITLE
Z2 Plus gets: "E3004: This package is for device z2_plus; this device is Z2"

### ISSUE THREAD

**Issue by Goidi** [z2-dev/android_device_zuk_z2_plus#146]
Hi, I have a Zuk Z2 Plus working right now with version: lineage-14.1-20170822-UNOFFICIAL-z2_plus.zip

My problem is I can't install  newer versions, the next one is 20170904 and the last one 20171014. I can't install any of them and I got "Error 7" and the following message: 

E3004: This package is for device z2_plus; this device is Z2

My device is Z2 Plus and I have a ROM for Z2 Plus working perfectly, does anyone know what is happening? Or have a similar problem?

Thanks

**Comment by AlvaroBrey** [comment]
You probably have an outdated or broken recovery. Flash the latest one (https://dl.twrp.me/z2_plus/) and try again.

**Comment by Goidi** [comment]
Álvaro, thank you very much, that was exactly my problem, I updated it and I could install the newest version. I had "TWRP Manager" app, I changed it for "Official TWRP App" and now is working!! Thank you again!!

Saludos desde México!!
