### ISSUE TITLE
Kernel panic on wifi

### ISSUE THREAD

**Issue by nsr8** [z2-dev/android_device_zuk_z2_plus#147]
ROM build date 20112017
Doing a clean install after erasing Dalvik, cache, system, and storage. boots up to sign in to requesting wifi access. Does not go beyond that screen. Screen is turned off and led notification lights up.

can't capture logs because adb doesn't recognize the device.

**Comment by AlvaroBrey** [comment]
If this only happens with wifi, it's likely related to your firmware/baseband. Please update your firmware to the latest available ZUI and try again.

I've also updated the release notes to clarify this.

**Comment by nsr8** [comment]
It was indeed caused by an old baseband. Updating baseband solved the issue. Thank you for your patience and support. Please delete/mark as solved this issue.

**Comment by AlvaroBrey** [comment]
Thanks for reporting back!

**Comment by vovata** [comment]
Sorry, could you please explain what it means to update the firmware to the latest available ZUI? I wish to keep all my settings as they are in release 20171014. Shall I reinitialize everything in order to install release 20171120?

**Comment by AlvaroBrey** [comment]
@vovata Either flash the latest ZUI and then flash LOS back, or find on the forums some package to update the firmware, there are probably some zips around there.
In any case, you absolutely must update your firmware in order to stop the crashes.
