### ISSUE TITLE
Logcat spam with Divinebeats 9.0

### ISSUE THREAD

**Issue by UnskilledHoss** [z2-dev/android_device_zuk_z2_plus#15]
Hello, I have posted about this issue on the forum too but I'll paste the text here for easy reference:

I have encountered an issue regarding this rom and divnebeats. When divinebeats is installed, the logcat is spammed with "QMI_FW  : xport_reg Failed for service_id=0x35 version=0x1001 on 14". Google has revealed the issue on the OnePlus 3, but it's unrelated to divinebeats.

The same issue is present on both the latest version (20170217) and fedor's last build. (I wanted to test the first version too, but the downloaded zip was corrupted)

Steps I took to reproduce issue:

- Wiped Data, Cache, Dalvik Cache and System using Fedor's TWRP.
- Flashed ROM and divinebeats 9.0
- Rebooted
- Activated adb in development settings
- Rebooted
- Unlocked and waited on home screen for 10 seconds

PS. With 20170217, the phone seems to overheat even when idle. Perhaps this is related?

Attached are the logcats from your build and fedor's build. (not sure if the dmesg for fedor's build is correct though)

[fedordmesg.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785145/fedordmesg.txt)
[fedorlogcat.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785146/fedorlogcat.txt)
[v2dmesg.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785148/v2dmesg.txt)
[v2logcat.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785147/v2logcat.txt)

**Comment by AlvaroBrey** [comment]
I don't support third party addons, sorry.
Closing as invalid

**Comment by UnskilledHoss** [comment]
My apologies in that case. Is the only solution not to use it?

**Comment by AlvaroBrey** [comment]
It seems that way. Furthermore, a quick google search suggest that your overheating/battery issues can be related to the addon.

**Comment by UnskilledHoss** [comment]
yes, after some testing it seems my battery is nice and cool again. I thought i looked into it properly but i guess not. Thanks again for maintaining this device :)
