### ISSUE TITLE
Tap to go back prevents adding new fingerprints

### ISSUE THREAD

**Issue by andrepd** [z2-dev/android_device_zuk_z2_plus#16]
Since tapping the home button is equivalent to pressing the back button, when adding fingerprints when you place your finger to register the print the phone goes back to the previous screen, ending the process. This prevents th e user from adding new fingerprints. 

Disabling the back button in that screen would fix the issue, since that screen has a back arrow on the top bar, so the physical button is not necessary.

**Comment by AlvaroBrey** [comment]
Actually, the back button IS disabled in the fingerprint screen, and there's no arrow in the top bar :\\
You mean this screen attached here, right?
![photo_2017-02-18_22-36-51](https://cloud.githubusercontent.com/assets/8677743/23097060/cf53d60c-f62a-11e6-819a-30f5c80ba8f0.jpg)

**Comment by marchi19217** [comment]
To clarify on first button touch if you tap and lift instead of tap and hold as directed by the application it will issue a back command

This is not really a bug and if you follow the on screen directions there are no issues

**Comment by andrepd** [comment]
Yes, my bad, there is no back button. Still since press=home you can safely disable tap=back on that screen.

I get this behaviour whether I tap and lift, or tap and hold. I'm on 20170211 so I can't confirm if this issue remains in the latest version. 

Since nobody I know of reported this bug, I'm inclined to think it may not be a problem with this ROM. Still I thought I'd report it.
