### ISSUE TITLE
LineageOS Browser Text Input 

### ISSUE THREAD

**Issue by marchi19217** [z2-dev/android_device_zuk_z2_plus#19]
User text input into a website field is invisible until you tap away from the field. The onscreen keyboard also becomes very slow/unresponsive

**Comment by AlvaroBrey** [comment]
I've noticed this bug as well, gotta investigate if it's a generalized LOS bug or if it's just this device.

**Comment by AlvaroBrey** [comment]
Solved by using Gello as default browser (52e1983e8aee7ee85570de3816e7e9ed71f2c8b4)
