### ISSUE TITLE
Miracast problems

### ISSUE THREAD

**Issue by luci-11** [z2-dev/android_device_zuk_z2_plus#22]
First pairing with cast receiver goes well but nothing is shown on tv, then disconnecting and reconnecting does nothing (receiver remains in listening state)

Steps to reproduce first pairing issue:
1- it is the first time that you launch "cast" to smartTV (don't have a cast stick to doublecheck) - with cast screen option enabled    (after a reboot is also ok)
2- phone will make connection to the smartTV but nothing can be seen on the display

Steps to reproduce "common behaviour":
3- try to connect to a receiver
4- receiver remains in listening state - no handshake between devices

Sorry for complete log but I really don't know how to "filter" critical lines for this issue.
Structure of log:

--log started--

- pressed "cast" for first pairing  (point 1)
- got black tv screen (point 2)
- disconnected and trying to reconnect (point 3)
- stuck situation (point 4)

--log stopped--

If needed i can attach also a log of a working device for comparison.

 
[logmiracast.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/788112/logmiracast.txt)

**Comment by AlvaroBrey** [comment]
Thank you! will take a look at it when I can.
Also, FYI, full log is always preferred. Sometimes users filter out what they think isn't important, and remove things that are useful! :)
I also appreciate the clear descriptions and  log structure. I wish all bug reports where like this!

**Comment by poad42** [comment]
Miracast is a nougat bug

https://github.com/nitrogen-project/android_frameworks_av/commit/a1816ac70c688f22b292bd5b38a52baa4dd0668e

https://github.com/nitrogen-project/android_frameworks_av/commit/51df39848bea8ecf4a02ab1ae6d3699c7296f56a

That'll fix it.

**Comment by wajeehuzkhan** [comment]
Using Discovery Rom running on 7.1.2 and screen mirroring works maybe you can check there 
sorry have no knowledge of programming myself else would have loved to help

**Comment by NedelchevT** [comment]
Optimum pro has fixed this issue in Jaguar maybe you can get some help from him.

**Comment by AlvaroBrey** [comment]
@wajeehuzkhan @NedelchevT If I upload a test build, are you willing to test if it's working?

**Comment by NedelchevT** [comment]
Sure, but I won't be able till 28th of  may.

**Comment by wajeehuzkhan** [comment]
@ontherunvaro of course i will be more than willing to test your rom but currently i dont own a TV as shifted to another country for job.  for anything else count me in for testing

**Comment by AlvaroBrey** [comment]
Hello, can anyone confirm if miracast is working on the latest release (20170526)?

**Comment by NedelchevT** [comment]
I was finaly able to test this. Works flawlessly, thank you.
