### ISSUE TITLE
Wave and pick-up gestures not working to wake ambient display

### ISSUE THREAD

**Issue by lazaroid** [z2-dev/android_device_zuk_z2_plus#23]
Looking through the revisions to the device/zuk/z2_plus/doze subdirectory, it looks like things have been renamed several times and I _think_ this is why it currently doesn't work (I'm still working out how the device code all fits together).

In doze/Android.mk, LOCAL_PACKAGE_NAME := XiaomiDoze

but in device.mk, it is included (or not...) with PRODUCT_PACKAGES += ZukDoze

I suspect the implementation came from a Xiaomi ROM and was partially renamed. There are also references to Xiaomi in:
doze/AndroidManifest.xml (android:permission="XiaomiDozeService")
doze/src/com/cyanogenmod/settings/doze/DozeReceiver.java (TAG = "XiaomiDoze")
doze/src/com/cyanogenmod/settings/doze/BootCompletedReceiver.java (TAG = "XiaomiDoze")

I don't know whether it's simply a case of replacing Xiaomi with Zuk in each place and it will all magically work or not. Having replaced all mentions of Xiaomi under doze/ with Zuk, I've just rebuilt and I now have /system/priv-app/ZukDoze/ZukDoze.apk which I didn't have previously. (I won't have a chance to test this version for a few days, though.)

**Comment by AlvaroBrey** [comment]
Thanks, I'll take a look at it :)

**Comment by lazaroid** [comment]
Not had a chance to install the full ROM yet but copying the newly created ZukDoze.apk into /system-priv-app/ZukDoze/ (on your 17022017 release) and it seems to be working as expected. I.e., I get the full set of Ambient Display options and both hand wave and pick-up activate it if turned on.

**Comment by ontherunvaro** [comment]
Do you want to do a PR? That way you'll show up in the commits. If you don't I'll thank you anyway in the commit messages but you won't appear as author.

**Comment by AlvaroBrey** [comment]
Done in 7104110336c03368bbf4bd488ed57c4a858f90f1, thank you.

**Comment by lazaroid** [comment]
Thanks for applying these changes.

I would have put in a pull request but that would have involved working out
how to do one first! ;-) I've generally just pulled stuff from github and
used as it is.

I should look into how to do pull requests in case I manage to come up with
something else useful!

Cheers,

Laz
