### ISSUE TITLE
Fix setup-makefiles.sh

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#24]
setup-makefiles.sh is pretty damn broken, and it's useless right now.

**Comment by sachk** [comment]
Please do this, or at least give us your makefiles.

**Comment by AlvaroBrey** [comment]
@sachk what? vendor makefiles are up to date in https://github.com/ontherunvaro/proprietary_vendor_zuk_z2_plus
