### ISSUE TITLE
Video recording frame freeze

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#26]
After recording 20-30 seconds of video footage, the frame freezes. If camera is restarted, it is still frozen until phone restart.
Logs from @luci-11:
[videostuck30_stock.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/793305/videostuck30_stock.txt)
[videostuck_stock.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/793306/videostuck_stock.txt)

**Comment by buuuchi408** [comment]
no freeze when use footej camera instead of stock camera or bacon camera app.

**Comment by SuperLamic** [comment]
Confirming https://review.lineageos.org/#/c/165102/ fixes this.

**Comment by AlvaroBrey** [comment]
Solved by upstream changes ( https://review.lineageos.org/#/c/165102/ ) and relevant BoardConfig flag.
