### ISSUE TITLE
Better way of controlling utouch settings

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#31]
I need to find a way to better handle U-Touch gesture settings and the like.  Current way (button overlay) is not extensible and fucks up possible upstream changes to button settings.

**Comment by ICHx** [comment]
I found that selecting any action to open camera would turn out nothing

**Comment by marchi19217** [comment]
Thought it wouldn't be worth starting a new thread but the long press, double tap and swipe right options are not working

**Comment by AlvaroBrey** [comment]
@marchi19217 *some* of the actions arent working (like launch camera) but the swipe right, double tap and long press triggers do work. I'm still investigating why some actions don't work.

**Comment by AlvaroBrey** [comment]
Closing for now as I've been told by the LOS people there's no proper way of doing this for now.
