### ISSUE TITLE
Network Connection Failed

### ISSUE THREAD

**Issue by marchi19217** [z2-dev/android_device_zuk_z2_plus#32]
I get "Network Connection Failed" when I wake from sleep on newest build, looks like it has something to do with the second SIM

**Comment by marchi19217** [comment]
[bugreport-NOF26W-2017-03-14-16-43-55.zip](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/840512/bugreport-NOF26W-2017-03-14-16-43-55.zip)

**Comment by marchi19217** [comment]
Seems to happen when switching Wifi/cells/wake from sleep

**Comment by AlvaroBrey** [comment]
Hello, is this still happening?  If so, would you be willing to test a build to see if it's fixed?

**Comment by marchi19217** [comment]
I have done a CLEAN flash of the latest build and could not reproduce

Tried;
- Adding second SIM
- Switching between SIM cards
- Removing second SIM
- Enabling/disabling Wifi

**Comment by AlvaroBrey** [comment]
Closed as not reproducible
