### ISSUE TITLE
Blur background is not work

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#34]
Blur background that a setting of Screen lock is not work.

**Comment by AlvaroBrey** [comment]
It's working for me. Which build are you on?

**Comment by 508279079** [comment]
Now I am useing the version 14.1-20170303.After I set a lock screen wallpaper,Blur background is not work.

**Comment by AlvaroBrey** [comment]
How are you setting the lockscreen wallpaper?

**Comment by 508279079** [comment]
I use NovaLauncher.

**Comment by AlvaroBrey** [comment]
Can you set a lockscreen wallpaper in Nova? Or do you mean the regular wallpaper? (i.e. not specifically for lockscreen)
I use Nova too, and background blur on lockscreen is working fine for me.

**Comment by 508279079** [comment]
Maybe because I modified the system file. Wait me to flash the rom and test again.
