### ISSUE TITLE
Cannot charge when power off

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#35]
Cannot charge when power off:
- ROM build version (date):20170303
- Steps to reproduce:Power off and charge.It will power on.(关机并充电，手机会自动开机）

**Comment by ICHx** [comment]
I can say I see the same trouble.  The phone would first show the stock off-charging screen.  After a few seconds, it would power on automatically

**Comment by marchi19217** [comment]
So does this happen with the stock rom? I would think this stage is way before the kernel even kicks in

**Comment by marchi19217** [comment]
Okay, this may provide a solution;
http://stackoverflow.com/questions/13515094/charging-an-android-mobile-phone-in-power-off-state

**Comment by poad42** [comment]
You need to build libhealthd for offline charging to work.

**Comment by AlvaroBrey** [comment]
@poad42 It's already being built in the charger-test branch, but it still doesn't work.

**Comment by NedelchevT** [comment]
Have you seen this? https://github.com/faizauthar12/android_device_zuk_z2_plus/commit/2aed35c272562dcc6b761f3265edebdb0a0138f9

**Comment by AlvaroBrey** [comment]
@NedelchevT yes, all of the devs (including me) have tried something similar to that at some time but we can't get it to work. It's a mystery as of now :\

**Comment by faizauthar12** [comment]
@NedelchevT it's just a placebo repo for jenkins..

So whatever you seen there, it just a testing sh*t

_Sent from my ZUK Z2 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AlvaroBrey** [comment]
Fixed from 20170930
