### ISSUE TITLE
GPS Overheating

### ISSUE THREAD

**Issue by marchi19217** [z2-dev/android_device_zuk_z2_plus#43]
Phone gets abnormally hot when there is long GPS use

Running Google maps for a 30 minute trip should show this behaviour

***
If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
I'm not sure this is a bug, this has happened with every phone I've owned. Constant screen on + cpu usage from GPS will do that.
