### ISSUE TITLE
[feature suggest] ZRAM , ksm switch

### ISSUE THREAD

**Issue by ICHx** [z2-dev/android_device_zuk_z2_plus#44]
I would like to have an option for enabling either zram or ksm so that we can achieve better performance in performing memory intensive jobs in our phones.

**Comment by AlvaroBrey** [comment]
No feature requests, sorry.

**Comment by ICHx** [comment]
It's part of lineageos

**Comment by AlvaroBrey** [comment]
zram/ksm are available in LineageOS, but the option to toggle them on/off from the ROM isn't. I might consider enabling them in the future, but "I would like to have an option to..." is *definitely* a feature request.

**Comment by ICHx** [comment]
ok
