### ISSUE TITLE
File Manger Missing

### ISSUE THREAD

**Issue by marchi19217** [z2-dev/android_device_zuk_z2_plus#45]
Lineage OS file manager is missing from latest build

**Comment by AlvaroBrey** [comment]
The classic  cm-file-manager has been deprecated. Builds now come with AOSP file manager. 
https://review.lineageos.org/#/c/163484/

If you need a more advanced file manager you should install one of your liking from playstore or similar sources.

**Comment by marchi19217** [comment]
Agreed however the AOSP file manager is not included in the latest build either?

**Comment by AlvaroBrey** [comment]
@marchi19217 Yes it is. In english it's called "Files", no idea about other languages. The default icon is a blue circle with a white folder.
