### ISSUE TITLE
Use Snap camera

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#46]
Camera2 is very, very simple. Snap is a nice opensource alternative mantained by LineageOS with many more features.

Replacing Camera2 with Snap would be nice.

**Comment by Kvnaevi** [comment]
whether the latest rom yours already using snap camera? how to record slow motion? if they force close?

**Comment by Kvnaevi** [comment]
Any link for snap camera?

**Comment by AlvaroBrey** [comment]
Done as of release 20170324

**Comment by Kvnaevi** [comment]
How about slow motion?

**Comment by AlvaroBrey** [comment]
@Kvnaevi it's working
