### ISSUE TITLE
Trim not automatically working

### ISSUE THREAD

**Issue by ICHx** [z2-dev/android_device_zuk_z2_plus#51]
The ROM is smooth on my phone,but quickly become slow.  I found some problem related to TRIM
After downloading the fstrim app, it shows that 40gb are trimmed the for the first time I trim /data 
Seeing that, I further looked around the system.  I found that the discard flag is not on for any partition Other than /system

z2_plus:/ $ mount|grep discard
/dev/block/bootdevice/by-name/system on /system type ext4 (ro,seclabel,relatime,discard,data=ordered)
z2_plus:/ $

ROM build: 20170314 zuk z2 plus

**Comment by AlvaroBrey** [comment]
If I recall correctly, the `discard` flag activates realtime trim, which is not desirable by any means. In fact, that flag shouldn't be on /system either.
As for why /data is not getting trimmed, I will have to investigate a bit, but it should automatically be done by the system.

**Comment by AlvaroBrey** [comment]
Android automatically trims by default and `vdc fstrim dotrim` works fine. Unless you can provide some more info, this issue is closed.

**Comment by ICHx** [comment]
https://holland.pk/utbgwfk3
You may prove me wrong.

**Comment by ICHx** [comment]
Just tested,  it might be shown that dotrim has little effect to /data currently.  
I had first run a dotrim and then did a fstrim for the observation.

**Comment by AlvaroBrey** [comment]
As stated before, trim system is working correctly from the tests I've done. For all I know you might have deleted 40gb of files and not waited a sensible amount of time for trim (on desktop systems trim is usually recommended once a week).
In a week or so I'll check  again if my untrimmed space is big (it wasn't when I checked today), and then I'll confirm or disprove my findings.
Either way I'm _not_ adding realtime trimming, as it would impact fs performance negatively.

**Comment by AlvaroBrey** [comment]
@ICHx By the way are you using ext4 or f2fs?

**Comment by ICHx** [comment]
ext4

**Comment by AlvaroBrey** [comment]
@ICHx after investigating a bit and talking to LOS mantainers, turns out TRIM is triggered only under certain conditions (like the phone being plugged in and inactive).
It also seems it's not working on hardware encrypted devices. Do you happen to have encryption set up?
