### ISSUE TITLE
Camera is not available in 20170324 Release

### ISSUE THREAD

**Issue by kpcz** [z2-dev/android_device_zuk_z2_plus#52]
It is impossible to open stock (snap) camera Or use any camera app from play store. Error - cannot connect to camera. Also Flashlight doesnt work.

_Edit by repo owner: removed log from comment and attached file instead_
[nocamera_log.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/868319/nocamera_log.txt)

**Comment by AlvaroBrey** [comment]
Fixed in hotfix release.
