### ISSUE TITLE
OTG is not working

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#59]
- ROM build version (date):20170324
无法使用U盘

**Comment by AlvaroBrey** [comment]
Hi @508279079, OTG is working perfectly for me on the latest release. What device are you trying to use, and with what adapter?

**Comment by jtnmartinho** [comment]
Hi! I've tried it and it's working for me too - 20170324 hotfix .

**Comment by 508279079** [comment]
Maybe I used a wrong app.
