### ISSUE TITLE
VoLTE isn't working

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#6]
VoLTE doesn't work as reported by several users.

**Comment by AlvaroBrey** [comment]
Enough users report broken VoLTE to consider it verified.

**Comment by michaellanbin** [comment]
[v2.pdf](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785567/v2.pdf)
[20170219-hd-call10086.zip](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785568/20170219-hd-call10086.zip)
[20170219-normal-call10086.zip](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/785569/20170219-normal-call10086.zip)
hello 
ontherunvaro
attach you some CMCC normalcall & hd call logs and CMCC volte white paper, hope some help for you , if useless ignore this, thank you  (baseband software 2.5.334)

**Comment by marchi19217** [comment]
If you can compare the zip files you may find a solution;
https://forum.xda-developers.com/zuk-z2-pro/development/leaked-rom-android-n-7-0-z2plus-z2131-t3500375/post69875936

**Comment by michaellanbin** [comment]
http://zukfans.eu/community/threads/7-1-x-z2-unofficial-dirty-unicorns-by-davidevinavil.4279/page-54

Someone has tried the naphtha’s rom and volte is working. It’s a good news.
And I noticed peoples begun to write IMS code in  AICP gemini project , we can find it in changelogs.

Thanks every developers!
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AlvaroBrey** [comment]
@michaellanbin I have read that thread and reports are that VoLTE is *not* working, I don't  know where you read the contrary.

**Comment by AlvaroBrey** [comment]
Closing as multiple users report that VoLTE is in fact working
