### ISSUE TITLE
Do not turn off the power saving mode, after charging the smartphone

### ISSUE THREAD

**Issue by denka977** [z2-dev/android_device_zuk_z2_plus#61]
When the battery is low, the power saving mode is activated, which is not turned off after the smartphone is charged. Visually it will be turned off, but the interface will not work smoothly, and applications will open for a long time. You can fix this if you turn on and immediately turn off the power saving mode in the settings.

**How to recreate a bug:**
1. Discharge the battery of the smartphone, so that it turns off with the mode turned on.
2. turn on your smartphone for charging.
3. The interface will not work smoothly.

**Comment by AlvaroBrey** [comment]
Hello, does this error persist in the latest release (20170420)?

**Comment by AlvaroBrey** [comment]
Closed for lack of response or other reports.
