### ISSUE TITLE
GPS issues

### ISSUE THREAD

**Issue by AlvaroBrey** [z2-dev/android_device_zuk_z2_plus#64]
GPS  configuration is not initialized properly in any custom ROM. Thanks to invaluable information provided by @bugDoe, we know that:

1. Flashing a stock Chinese  ROM via QFIL (1.9x and 2.5x were tested) fixes the GPS (faster lock and higher accuracy). Booting the ROM once after flashing is required.
2. Flashing a custom ROM after that doesn't break GPS.
3. Erasing the `modemst1` partition does break GPS.

Conclusions:

- Whatever is in `modemst1` is generated properly in stock ROMs but not in customs.

***
- ROM build version (date): all of them
- Steps to reproduce:

1. Erase `modemst1`
2. GPS is now fucked

**Comment by bugDoe** [comment]
Seems like flashing the DarkMoon kernel by DD3boh fixes the GPS partition init problem.
Kernel tested is release 002: https://zukfans.eu/community/threads/darkmoon-kernel-nougat-ubertc-3-18-48.5778/unread

Seems like the problem is something kernel related.

**Comment by bugDoe** [comment]
Another update about this: I have to sadly admit that Mokee 6.0.1 Release version can also manage to init and fix GPS correctly. I'm going to try also Mokee based on Nougat to check if it will work too. Anyway, I think checking Mokee's 6 kernel could give some hints.

**Comment by bugDoe** [comment]
I tested PacROM by Fedor917 (Android 6.0.1 based) and also this custom ROM works perfectly with fixing the initialization of the GPS. I think something is missed with the update to Nougat.
Mokee 7.1 nightlies also aren't working with GPS init like all 7.1 android based roms (except stock)

I hope this helps more on finding the problem.

**Comment by denka977** [comment]
Installed the kernel DarkMoon kernel by DD3boh, but the satellite catches badly. With 20 active satellites, the status is "No fix".

**Comment by Erromango** [comment]
Some weird things here. I'm having the gps issue in a different way. Once i can fix the gps signal then for a while i can get fix fast and accurate. then maybe hours later my gps get fucked again. I installed LOS after QFIL chinese stock ROM so i guess my modemst1 is okay.

**Comment by AlvaroBrey** [comment]
@Erromango Yes, that seems to be the case. I think gps breaks when AGPS data is updated.
Can you take a backup of `modemst1` before and after it breaks, just to confirm that contents are different?

**Comment by Erromango** [comment]
@ontherunvaro Here's the test. i backup modemst1 by following code: dd if=/dev/block/mmcblk0p10 if=/sdcard/modemst1.bin bs=512
and compare files with winhex.
one backup is after a 3 seconds fix and another is after a 1:41 fix(same position) and there's no difference between the 2 files.

**Comment by Erromango** [comment]
Edit gps.conf via topntp fix it.

**Comment by AlvaroBrey** [comment]
@Erromango what edits exactly?

**Comment by Erromango** [comment]
I'm in China so i choose cn.pool.ntp.org

```
#####################################
#                                   #
#       This gps.conf file is       #
#             created by            #
#      TopNTP - the app by Zatta    #
#         provided by Crypted       #
#                                   #
#####################################
NTP_SERVER=cn.pool.ntp.org
AGPS=http://xtra3.gpsonextra.net/xtra.bin
XTRA_SERVER_1=http://xtra3.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra4.gpsonextra.net/xtra.bin
DEFAULT_AGPS_ENABLE=TRUE
DEFAULT_USER_PLANE=TRUE
DEFAULT_SSL_ENABLE=FALSE
INTERMEDIATE_POS=1
ACCURACY_THRES=3000
QOS_ACCURACY=50
QOS_TIME_OUT_AGPS=95
QOS_TIME_OUT_STANDALONE=80
QosHorizontalThreshold=1000
QosVerticalThreshold=500
SUPL_HOST=supl.google.com
SUPL_PORT=7276
SUPL_SECURE_PORT=7275
SUPL_NO_SECURE_PORT=3425
SUPL_TLS_HOST=FQDN
SUPL_TLS_CERT=/etc/SuplRootCert
REPORT_POSITION_USE_SUPL_REFLOC=1
AssistMethodType=1
AgpsUse=1
AgpsServerType=1
AgpsServerIp=3232235555
AgpsMtConf=0
AgpsMtResponseType=1
CURRENT_CARRIER=common
PHONE_TYPE=UMTS
```

_Edit by repo owner (2017-06-03): formatting_

**Comment by AlvaroBrey** [comment]
This has mostly been fixed by the following commits:

- bb0eabeee6618307c97d46f398600ba26714750c
- https://github.com/z2plus-dev/proprietary_vendor_zuk_z2_plus/commit/15c5ac1ffda3ab56ecff1496ed41f7b8cbde0a61

GPS accuracy and fix time is now much, much better, though only if there's mobile data available (required for aGPS).

This will be included in the next release.

**Comment by denka977** [comment]
Problems with GPS should not return after a while?

**Comment by AlvaroBrey** [comment]
@denka977 apparently it's fixed for good, but only time will tell
