### ISSUE TITLE
Camera Event DAEMON DIED error

### ISSUE THREAD

**Issue by kpcz** [z2-dev/android_device_zuk_z2_plus#65]
ROM 14.1-20170414

Both camera app tested, Snap and snapcamera HDR, randomly dies with error "The media server had died" and camera app crashes. On Snap camera often on slow mo recording, on Snapcamera HDR, on ordinary camera. Never had these on previous releses (previous relese I used: 20170330) Installed 14.1-20170414 after DU rom, but made full wipe, also data.  Attached log.

[LOG15042017.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/923877/LOG15042017.txt)

**Comment by AlvaroBrey** [comment]
Is this still happening on the latest release? I could not reproduce it.

**Comment by kpcz** [comment]
Hi, no. I think It was some kind of flashing issue. So you can close the issue. Thanks.
