### ISSUE TITLE
Microphone isssue in Viber/Skype

### ISSUE THREAD

**Issue by NedelchevT** [z2-dev/android_device_zuk_z2_plus#66]
The microphone is not working when i try to use speakerphone in Viber.
Here is logcat. (https://pastebin.com/Dbp1JX2B)

**Comment by omoxiroyi** [comment]
I also find the same issue..

**Comment by Kumar-Kishan** [comment]
Yeah same issue here too...
Unable to use microphone in viber in loudspeaker and video call

**Comment by gelad** [comment]
Same in Skype.

**Comment by AlvaroBrey** [comment]
I've just published [release 20170519 ](https://github.com/ontherunvaro/android_device_zuk_z2_plus/releases/tag/20170519), which contains some changes to audio configs. Please tell me if the problem persists.

**Comment by karasat** [comment]
After update to release 20170519 the microphone works fine (checked in Viber). Thx for great work!

**Comment by gelad** [comment]
Tested in Skype - works fine too. Thanks!

**Comment by AlvaroBrey** [comment]
Perfect, thank you :) Closing this
