### ISSUE TITLE
LTE it's not working

### ISSUE THREAD

**Issue by lucasfm96** [z2-dev/android_device_zuk_z2_plus#67]
Only works h and h+

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date): 04/14/2017
- logcat (pastebin link): https://1drv.ms/t/s!AokC-yJ7RNqir8kDTAvtZKeQZ2aMGw
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
![screenshot_20170417-155431](https://cloud.githubusercontent.com/assets/8677743/25091201/1dc71486-2388-11e7-9517-bd5007dabd6f.png)
It's working fine for me. Can you post a radio logcat?
`adb logcat -b radio`

**Comment by lucasfm96** [comment]
Done. I used matlog.

**Comment by joshhsoj** [comment]
Hi ,
I have the same problem . 
LTE never working . Only H , H+ .
Rom build version : 04/14/2017
Now my provider in WIND (italy) , until 18 of april was TIM  . Both never worked in LTE .
Smartphone is ZUK Z2 plus

I post my radio logcat
[logcat.txt](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/948705/logcat.txt)

Thank you

**Comment by lucasfm96** [comment]
I was able to fix it, just got back to stock, then put the custom again. It worked.

**Comment by joshhsoj** [comment]
Thank's 4 the ultra rapid answer .


One of these days I try .


[😉]  [👌]


Marco

________________________________
Da: lucasfm96 <notifications@github.com>
Inviato: sabato 22 aprile 2017 06:28:57
A: ontherunvaro/android_device_zuk_z2_plus
Cc: joshhsoj; Comment
Oggetto: Re: [ontherunvaro/android_device_zuk_z2_plus] LTE it's not working (#67)


I was able to fix it, just got back to stock, then put the custom again. It worked.

**Comment by Aischel** [comment]
After i go back to stock and put the custom again, LTE/4G not work only Edge, H, H+

My radio logcat 
[logcat](https://drive.google.com/open?id=0B71tNxTqe5tFbTg3RldSaFlxMGs)
