### ISSUE TITLE
Music information not showing on Bluetooth media

### ISSUE THREAD

**Issue by lucasfm96** [z2-dev/android_device_zuk_z2_plus#68]
The music information it's missing on my car, connected by Bluetooth

***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date): 04/14/2017
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce: Connect to a Bluetooth media, and reproduce any song. ( I'm using Deezer, but it was working with stock rom )

**Comment by AlvaroBrey** [comment]
My car is displaying the info without problem. Does this problem persist for you on the latest release (20170420)?
