### ISSUE TITLE
Not able to sign in on public wifi

### ISSUE THREAD

**Issue by akavkl** [z2-dev/android_device_zuk_z2_plus#69]
Every time I have to shutdown my phone then boot it up to sign in.

**Comment by AlvaroBrey** [comment]
This issue needs logs and more info (ROM version, type of wifi network, etc.). I am able to sign in on public wifi networks without any problem.
Please provide more info or this issue will  be closed.

**Comment by akavkl** [comment]
Can't provide log now cause I'm on RR official now but can provide detailed info on problem.
ROM version - 20/04/17
Tested on Starbucks WiFi
Provider - Tata Docomo
Type of connection is, "sign in to network" dialog pops up after connecting to WiFi.
On this ROM above dialog doesn't pop up and to make it pop up I have to shutdown the phone every time.
Note, SHUTDOWN. Not even restarting works.

**Comment by akavkl** [comment]
This problem is not there on Dirty Unicorns by davidevinavil and official RR.

**Comment by AlvaroBrey** [comment]
@akavkl The dialog doesn't popup? I am pretty sure you can get to the signin just by opening the browser and going to any website, you will be redirected to signin page.
Either way, "can't sign in" is a pretty different issue to "the sign-in notification doesn't appear".

**Comment by akavkl** [comment]
Tried that, didn't work.

**Comment by AlvaroBrey** [comment]
@akavkl what does "didn't work" mean? Did it not forward you to the signin page? Did it crash? Or something else?

**Comment by akavkl** [comment]
Shows no internet connection

**Comment by AlvaroBrey** [comment]
Closed for lack of logs and no other user reports.
