### ISSUE TITLE
U-touch long tap isn't working

### ISSUE THREAD

**Issue by SistemaKrasho** [z2-dev/android_device_zuk_z2_plus#70]
ROM build: 20170414
Kernel: 3.18.48-DarkMoon-Kernel-Zuk-Z2-Release-002+haha@DD3Boh
logcat (relevant part): https://pastebin.com/hgKrMmEY
dmesg (relevant part): https://pastebin.com/C3y9WAXR

U-touch long tap isn't working at all, i.e. actions are not being triggered for some reason. The key event **is** being forwarded.

**Reproduction steps:**
1. Go to Settings -> Buttons
2. Under U-touch, set Long tap to any of the available actions
3. Touch and hold your finger on the Home button for about half a second

**Comment by AlvaroBrey** [comment]
I do not support third part kernels, sorry
