### ISSUE TITLE
Cellular data is on by default

### ISSUE THREAD

**Issue by SistemaKrasho** [z2-dev/android_device_zuk_z2_plus#71]
After a fresh install, cellular data is active by default. It's quite the inconvenience since carriers may charge for simply enabling cellular data, like mine does.

Please consider changing this behaviour.

A workaround for users: remove all your SIM cards before flashing then disable cell data in settings before putting them back in.

**Comment by AlvaroBrey** [comment]
Probably upstream, I will try to investigate some more.

**Comment by wajeehuzkhan** [comment]
I can confirm this 
but this issue isnt exclusive to LOS but present in every custom rom i have tried

**Comment by AlvaroBrey** [comment]
Yes, I believe this is a design choice rather than a bug, since it's present on other phones on android 7.x as well. Closing for now.
