### ISSUE TITLE
Is not possible apply photo to a user of system

### ISSUE THREAD

**Issue by pensent** [z2-dev/android_device_zuk_z2_plus#72]
Hello, I have tried to put a previously created snap camera photo, and it is not possible to apply it to user profile photo. (I use the gallery application default)

ROM Build 04/14
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
Actually I can't seem to put *any* photo as a profile photo, not just those from camera. This is probably an upstream bug.

**Comment by AlvaroBrey** [comment]
Was an upstream bug, solved in release  20170420
