### ISSUE TITLE
LTE / 4G not work, only Edge, H, H+

### ISSUE THREAD

**Issue by Aischel** [z2-dev/android_device_zuk_z2_plus#73]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date): 14.1-20170420-UNOFFICIAL-z2_plus
- logcat (pastebin link): 
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce: update from 14.1-20170330-UNOFFICIAL-z2_plus

Baseband-Version: 9-00026-M8996FAAAANAZM-1.63821.1
Provider: Vodafone Germany

**Comment by AlvaroBrey** [comment]
See #67 and check if doing what solved that issue solves it for you (flashing stock via QFIL and then flashing LOS again)

**Comment by AlvaroBrey** [comment]
Closed for no response
