### ISSUE TITLE
Benchmark loss issue on 20/0417

### ISSUE THREAD

**Issue by akavkl** [z2-dev/android_device_zuk_z2_plus#74]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
Duplicate of #75
