### ISSUE TITLE
Connect to a WiFi without network, will use the data network

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#78]
- ROM build version (date):20170428
开着数据网络，连上WiFi，如果WiFi没有网络会直接使用数据网络。这样会造成流量的意外流失。
Open the data network, connected to WiFi. If WiFi does not have network, it will directly use the data network. This will cause unexpected loss of traffic.

**Comment by 508279079** [comment]
![screenshot_20170430-172935](https://cloud.githubusercontent.com/assets/15182238/25563353/692f9498-2d60-11e7-8533-303c04bbb4a4.png)
The screenshot shows the big croes were locked.

**Comment by AlvaroBrey** [comment]
This is not a bug, but an upstream design choice. 
Also, please do not reuse old issues, open new ones instead.
