### ISSUE TITLE
CPU monitor apps show 2 cores as off when they're not

### ISSUE THREAD

**Issue by 508279079** [z2-dev/android_device_zuk_z2_plus#79]
- ROM build version (date):20170428

当温度升到50℃以上，CPU的两个大核心会被锁住。即使温度降低到35℃，也得重启设备才会恢复正常。
When the temperature rises above 50 ℃, the CPU's two large cores will be locked. Even if the temperature dropped to 35 ℃, have to restart the device will return to normal.

![screenshot_20170430-172935](https://cloud.githubusercontent.com/assets/15182238/25563353/692f9498-2d60-11e7-8533-303c04bbb4a4.png)
The screenshot shows the big croes were locked.

**Comment by AlvaroBrey** [comment]
This issue has been discussed on the forums. The cores are not actually off, but there's a SElinux issue preventing monitor apps to read the info on them.

You can check this by temporarily disabling SELinux:
```
adb shell
su
setenforce 0
```
And after this, the CPU monitor will be able to show the correct values.

Please check if this is the case and report back.

**Comment by 508279079** [comment]
Yes, this is the case.
Thanks !

**Comment by AlvaroBrey** [comment]
It has been brought to my attention by the LOS folk that this has been intentionally blocked as a safety measure, and it happens on other LOS devices.

**Comment by AlvaroBrey** [comment]
This is working fine in latest release (20170811), therefore I'm closing this issue.
