### ISSUE TITLE
google  Network verification  problem

### ISSUE THREAD

**Issue by a515300040** [z2-dev/android_device_zuk_z2_plus#80]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):2017/4/28
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:  China has a network wall can not access any Google services。  so There is always a small x on the WiFi and mobile network.Does not affect the actual use。I usually use a software to eliminate it。But it needs root。So I hope you can open root permissions or Change the address of network validation or Make a separate patch。  thanks ！

**Comment by AlvaroBrey** [comment]
Nothing I can do about this. It's how Android/GAPPs work.
There's nothing preventing you from rooting the ROM and doing what you used to.

**Comment by a515300040** [comment]
http://uc1-apk.wdjcdn.com/7/97/ec174fe22fcfb15843910e15b6340977.apk  it is my bad english that you dont kown i say .this app  can eliminate it.   need  root

**Comment by AlvaroBrey** [comment]
You can root LOS using [the official root addon](https://mirrorbits.lineageos.org/su/addonsu-arm64-signed.zip) or any other root solution you might like (SuperSu, MagiskSu, etc.).

**Comment by a515300040** [comment]
if i use supersu , can i usetht ota

**Comment by AlvaroBrey** [comment]
Yes, but you will probably lose SuperSU after the update.
