### ISSUE TITLE
Dial code  *#*#4636#*#* don't working animore on build of 04/28/17

### ISSUE THREAD

**Issue by Di3s3l** [z2-dev/android_device_zuk_z2_plus#81]
Hi, normally use *#*#4636#*#* dial code to force my radio on "only LTE" (becouse LTE standart option in standard menu set it on preferred). With the new release the dial code don't work anymore (no message errore or warnig, only no action from the diale app).

My baseband is 2.0.c.1.9-00026-M8996FAAAANAZM-1 . I thik is the latest and have installed it on my device one of two previous LineageOS release, and with previous release was fully working. What kind of test and long i must provide to investigare this issue? Is my first time here.

**Comment by AlvaroBrey** [comment]
It's working fine for me on the latest release. You should try to get a logcat, but it probably will be solved if you do a clean flash.

**Comment by Di3s3l** [comment]
Came back home and install logcat app for investigate. Test intentional the issue and now is working. No reboot or other action, but in the past day i was unable to use the dialcode. Need more time to investigate, maybe was an isolate case?

**Comment by Di3s3l** [comment]
Came back home and install logcat app for investigate. Test intentional the issue and now is working. No reboot or other action, but in the past day i was unable to use the dialcode. Need more time to investigate, maybe was an isolate case?

**Comment by AlvaroBrey** [comment]
If you can't reproduce the bug and no one else has it, please leave this issue closed.

**Comment by Di3s3l** [comment]
The problem do not came anymore. Probably one app was conflicting with the dialer or was only my fault. Sorry for time you lose.
