### ISSUE TITLE
Video can't play required to do hw to sw every time in mx player and other player don't work

### ISSUE THREAD

**Issue by NIKETKING** [z2-dev/android_device_zuk_z2_plus#86]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
Please fill in the template you completely ignored. At least build date and steps to reproduce, because I can't even understand what you're saying.

**Comment by NIKETKING** [comment]
19 may 2017

**Comment by AlvaroBrey** [comment]
Thanks, but I also need steps to reproduce the issue, please.

**Comment by NIKETKING** [comment]
Go mx player play any video at that time sound not coming then it need to switch to sw in mx player . Other video player don't work

**Comment by AlvaroBrey** [comment]
I can play videos on MX Player and Gallery without any problem. I also tested both decoders in MX Player, both worked.
So it seems I need more info:

- Is this a clean install?
- What is the format of the videos you're trying to play (mp4/avi/flv)? What is the codec?
- Try to play [this](http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4) video which is the standard video test file and tell me what happens.
