### ISSUE TITLE
Last version of Google Camera crashes

### ISSUE THREAD

**Issue by gartstell** [z2-dev/android_device_zuk_z2_plus#9]
I install the latest version (02.14.2017)

I install the GAPPS 7.1 from 02.14.2017 and the Google Camera works OK. If I upgrade It in Play Store, it will crash. I also test FV 5 camera and work OK.

**Comment by AlvaroBrey** [comment]
Please attach a logcat, can't do anything without it.

**Comment by AlvaroBrey** [comment]
More reports of broken GCamera received, changing status to bug-verified

**Comment by marchi19217** [comment]
[bugreport-NMF26V-2017-02-22-08-42-25.zip](https://github.com/ontherunvaro/android_device_zuk_z2_plus/files/791599/bugreport-NMF26V-2017-02-22-08-42-25.zip)

Bug report attached

**Comment by AlvaroBrey** [comment]
Support for devices other than Nexus/Pixel series was removed by Google on February 16. https://en.wikipedia.org/wiki/Google_Camera

**Comment by callofdutyops** [comment]
One more question (pretty sorry for commenting on a `wotfix` bug), I'm sure that I can use the google camera on my oneplus one which is not a Nexus-like device. And I can also use google camera on my zuk with the origin ZUI.  Why this rom not? I really appreciate  your work on lineage. :)

**Comment by AlvaroBrey** [comment]
@callofdutyops No idea, but I'm not gonna try to solve it if Google has dropped support, especially when all other camera apps work.
