### ISSUE TITLE
Over heating over 10 to 15 min with casual work  19 may 2017

### ISSUE THREAD

**Issue by NIKETKING** [z2-dev/android_device_zuk_z2_plus#91]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
What was the "casual work"? What was the outside temperature like? Is this a clean install?

**Comment by NIKETKING** [comment]
10 to 15 min YouTube, browsing and gaming etc . But in stock zui it heat at same level but after 45 to 60 min,(marshmallow and nougat zui )

**Comment by AlvaroBrey** [comment]
Is this a clean installation?

**Comment by NIKETKING** [comment]
Yes

**Comment by AlvaroBrey** [comment]
Closed for no other reports, and also subjective

**Comment by NIKETKING** [comment]
What,😣😣😣😣 really over heat

**Comment by AlvaroBrey** [comment]
- You are the only one reporting this
- I don't have any overheating issues on my phone
- You also don't provide logs or objective data (i.e actual temperature)

Try clean installing. If it's still happening, it's probably not the ROM either, but some app you have installed or something like that.
