### ISSUE TITLE
OTA is not working (build 20170505)

### ISSUE THREAD

**Issue by onderaldemir** [z2-dev/android_device_zuk_z2_plus#92]
***
*ISSUES ARE NOT A DISCUSSION/SUPPORT FORUM*. Comments irrelevant to the issue WILL be removed.

If this issue is to report a bug, please provide everything you can from the list below:
- ROM build version (date):20170505
- logcat (pastebin link):
- dmesg (pastebin link):
- console-ramoops (pastebin link):
- Steps to reproduce:

**Comment by AlvaroBrey** [comment]
I'm gonna need a better description of the issue. What does 'is not working' mean exactly?

**Comment by onderaldemir** [comment]
check for updates but No updates available

**Comment by AlvaroBrey** [comment]
Fixed on the latest release
