### ISSUE TITLE
Google Assistant not working with "ok google"

### ISSUE THREAD

**Issue by BastianProsser** [z2-dev/android_device_zuk_z2_plus#94]
Google Assistant works, but it doesn't recognize the "ok google" command. To make GA work, I need to open it up manually. This is happening as of the latest LOS update.
I've retrained it plenty of times, turned the phone off and on, deactivate it and reactivate it, all of them without any kind of success.

**Comment by AlvaroBrey** [comment]
- Does it not work at all, or does it not work when the screen is off?
- Did it work in previous versions?
- Which GApps are you using? If OpenGapps, which package?
- Are you using a custom kernel?

**Comment by BastianProsser** [comment]
Sorry, I forgot to add things. 
-It's not working anywhere, be it screen on or off (it only works if you open the assistant manually)
-It worked previously, yes. As of the latest update, it stopped working.
-OpenGapps mini (the same I used when I first installed LOS.
-No custom Kernel.

**Comment by Erromango** [comment]
seems to be opengapps problem.
Clean flash bean gapps and it works fine

**Comment by oliverharrison** [comment]
I'm finding this as well. Here's how it works for me. First off, using Open GAPPS ARM64 full, from mid-May.

The only way I can get it to work consistently (using Nova, with OK Google setting on) is with OK Google voice detection (in the app) turned OFF, and then only from the homescreen.

How to reproduce:

Open Google app > Settings > Voice > 'OK Google' Detection
Say 'Ok Google' any time > OFF
Other settings are irrelevant
Go to home screen, say 'OK Google' --> Works
Within Assistant or Google App --> Works
Any other setting/screen --> Does not work

Hope that helps. I clean flashed bean GAPPS with no success.

**Comment by Erromango** [comment]
I mean you need to wipe system first then flash bean gapps
 Wipe data and factory reset didn't remove open gapps

**Comment by TotalSilence** [comment]
May be you should try clearing the Cache, browsing data. Worked for me when I was using this ROM.

**Comment by AlvaroBrey** [comment]
Confirmed working, needs Gapps nano or upper: won't work with Gapps pico.
