### ISSUE TITLE
Battery drain since version 20170526

### ISSUE THREAD

**Issue by SinisterMaya** [z2-dev/android_device_zuk_z2_plus#98]
Hi,

I have done my update using the automated updater since the early may version. Since my first flash of the rom , everything was working with no problem.

Since version of may 26, android system and android OS are draining my battery. their consumption represent for maybe 70% and cause the battery to drain even if in sleep with screen off. i would lose about 5-10% battery by just sitting on my desk doing nothing

can you guide me into providing a log that would help you ?

**Comment by SinisterMaya** [comment]
5-10% battery per hours*

**Comment by SinisterMaya** [comment]
here's a bug report I did. don't know if done properly : https://drive.google.com/folderview?id=0B5vSjHO9E8AjdVhEdkZwc2ZrNUE

**Comment by SinisterMaya** [comment]
FYI, rebooting the phone seems to fix the problem. will keep you updated whether or not this is a temporary fix or not.

**Comment by AlvaroBrey** [comment]
There's been no changes that may affect this. I suggest a clean flash.

**Comment by AlvaroBrey** [comment]
Any feedback? Did you do the clean flash I suggested?

**Comment by SinisterMaya** [comment]
Hi, the problem did not occur again so far. I am recreating every condition one by one to see if it could be app related. So far, i am enjoying your OS. great job !
