### ISSUE TITLE
shadowsocks didn't work

### ISSUE THREAD

**Issue by serephus** [z2-dev/android_device_zuk_z2_plus#99]
ss app can connect to ss server, but it won't work, any app using ss proxy will be offline. 
os version: 20170505

**Comment by resol341** [comment]
SS works for me.

**Comment by serephus** [comment]
There is a related issue in ss-android repository.
https://github.com/shadowsocks/shadowsocks-android/issues/1277
If you need more information, please tell me what you need, and perhaps where i can find them.

**Comment by serephus** [comment]
@resol341 I don't know exactly why, perhaps it's my network environment. btw, ss works fine in my pc.

**Comment by serephus** [comment]
Don't know why, but I've managed to solve this problem by reflashing this rom.
Now my os version is 20170603. So issue closed
